# Generated by Django 3.2.7 on 2021-09-21 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_categorie_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Product/secondary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Product/secondary'),
            preserve_default=False,
        ),
    ]
