# Generated by Django 3.2.7 on 2021-09-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210922_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='name',
        ),
    ]
