# Generated by Django 3.2.7 on 2021-09-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='Services')),
                ('description', models.TextField(blank=True, null=True)),
                ('posted', models.DateField(auto_now_add=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.type')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
