# Generated by Django 3.2.7 on 2021-09-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210922_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='Type',
        ),
    ]
