# Generated by Django 3.2.7 on 2021-09-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mqs',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
