# Generated by Django 3.2.7 on 2021-09-23 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210923_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
