# Generated by Django 3.2.7 on 2021-09-23 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_home_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slider',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
