# Generated by Django 3.2.7 on 2021-09-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20210924_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='home/Services')),
                ('name', models.CharField(max_length=200)),
                ('Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.type')),
            ],
        ),
    ]
