# Generated by Django 3.2.7 on 2021-09-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
