# Generated by Django 3.2.7 on 2021-09-26 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_remove_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Username',
        ),
        migrations.AddField(
            model_name='task',
            name='First_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
