# Generated by Django 3.2.7 on 2021-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20211128_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notre_équipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='team/photos')),
                ('Fonctionnement', models.TextField()),
            ],
        ),
    ]
